### ISSUE TITLE
Issues rendering StreamBlock and ListBlock as children of StreamField

### ISSUE THREAD

**Issue by roelio** [noripyt/wagtail-react-streamfield#1]
While trying the new stream field UI I encountered problems with the following model:
```
class Test(Page):
    content = StreamField([
        ('blockA', blocks.StreamBlock([
            ('subBlockA', blocks.BooleanBlock())
        ])),
        ('blockB', blocks.ListBlock(blocks.StructBlock([
            ("subBlockA", blocks.DecimalBlock()),
            ("subBlockB", blocks.TextBlock(required=False)),
        ])))
    ], blank=True)

    content_panels = Page.content_panels + [StreamFieldPanel("content")]
```
- When trying to add blockA I get an error in console: `wagtail-react-streamfield.js:1 Uncaught TypeError: Cannot read property 'subBlockA' of undefined`  (It seems to happen at https://github.com/noripyt/react-streamfield/blob/master/src/BlockContent.js#L117 because the `childBlocksByType` is empty)
- Adding blockB turns into a memory overflow issue and the tab freezes in Chrome (it looks like its creating an infinite of `BlockContent` components)

I wanted to add a testcase for you, but there is not test framework setup yet. Let me know if I can help in other ways.

**Comment by BertrandBordage** [comment]
Fixed by noripyt/react-streamfield@f2741f7463dfcea3beb1a5c542e3666f6ecad4ef.
Will be included in wagtail-react-streamfield shortly.

**Comment by roelio** [comment]
Tested it, and seems to be working! 
Needed to disable all the choosers and richtextfields for it to work, but you already noted this as a current issue.

**Comment by BertrandBordage** [comment]
Version 0.8.1 is released with a fix for this issue, as well as a better display of errors :smile:

**Comment by BertrandBordage** [comment]
Note that you can enable again your choosers and rich text blocks.
They now work, except for one detail: when you duplicate a chooser or rich text, the initial data is put in the new block, and not the current value. I’ll have to modify Draftail and the chooser panels to fix, but that’s an acceptable little bug for now :)
