### ISSUE TITLE
Chooser buttons don't work

### ISSUE THREAD

**Issue by arctangent** [noripyt/wagtail-react-streamfield#12]
Page chooser and Image chooser buttons do nothing when clicked.

**Comment by mwesterhof** [comment]
would you mind checking if it still doesn't work in the latest version? #9 was merged less than an hour ago, and it should (hopefully) tackle the image chooser issue, at least

**Comment by BertrandBordage** [comment]
Yes, these particular issues are fixed by upgrading to Wagtail 2.2.
