### ISSUE TITLE
No image thumbnails

### ISSUE THREAD

**Issue by grasshoppermouse** [noripyt/wagtail-react-streamfield#14]
When I have a StreamField with an ImageChooserBlock, I get thumbnail previews when I'm adding new images. But when I later edit the page, there are no thumbnails for any image. This is particularly inconvenient for image carousels (ListBlock containing an ImageChooserBlock) because I can't figure out which image I need to change or delete. Thanks for any advice!

![screen shot 2018-10-01 at 11 03 16 am](https://user-images.githubusercontent.com/7534138/46306652-b55fea00-c569-11e8-922b-e35a354e7f5e.png)

**Comment by BertrandBordage** [comment]
Could you confirm that you’re using Wagtail >= 2.2, wagtail-react-streamfield 0.8.6 with `wagtail-react-streamfield` before `wagtail.images` in `INSTALLED_APPS`?

**Comment by grasshoppermouse** [comment]
wagtail 2.2.2

`Successfully installed wagtail-react-streamfield-0.8.6`

```
INSTALLED_APPS = [
 
    'search',
    'department', # Delete this after transferring data
    'department2',
    'wagtail_react_streamfield',

    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.contrib.styleguide',
    'wagtail.contrib.postgres_search',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail.core',

    'modelcluster',
    'taggit',
    'osm_field',
    'wagtailosm',
    'wagtailaccessibility',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.contenttypes',
]
```

**Comment by BertrandBordage** [comment]
I see you have a visual glitch next to the delete icon. Did you make sure the browser cache is cleared, using ctrl+F5 on non-Apple OSes?

**Comment by grasshoppermouse** [comment]
> Did you make sure the browser cache is cleared

That did it. Thanks! The little square next to the delete icon is still there, though. I'm using Safari 12.0 on macOS 10.13.6.

On a side note, when do you anticipate this will be available for inlines?

**Comment by BertrandBordage** [comment]
@grasshoppermouse Great!
About the little square, could you share the HTML source of that square please?

I’m planning to release the equivalent for inlines within two weeks.
