### ISSUE TITLE
Rendering groups in streamfields icons

### ISSUE THREAD

**Issue by fpoulain** [noripyt/wagtail-react-streamfield#18]
Hi,

Thank you very much for this work.

it appears that the [group](http://docs.wagtail.io/en/v2.2.2/topics/streamfield.html?highlight=pagechooserblock#basic-block-types) attribute seems to be ignored in the editing interface. Is their some plans to add support for it?

**Comment by BertrandBordage** [comment]
Obviously yes, that was an omission, sorry about that.

**Comment by fpoulain** [comment]
Thanks for the feedback. I am sorry, I seems easy to fix but I have zero knowledge on reactjs for now.

**Comment by BertrandBordage** [comment]
Fixed by e364e712fd0bf38325fc534e4f4f0f244fadaa18 and released in 0.9.0.
