### ISSUE TITLE
Asterisk not being displayed for required fields in streamfield

### ISSUE THREAD

**Issue by dniegel** [noripyt/wagtail-react-streamfield#20]
For required fields in a streamfield, the 'required' asterisk is not displayed beside the fieldname.

![missing required asterisk](https://user-images.githubusercontent.com/45167324/48703403-d9e45400-ebf3-11e8-8e92-756727b22f5b.png)

Possible reason in wagtail-react-streamfield-extra.css

`.children-container .field label::after {
  content: '';
}`

**Comment by BertrandBordage** [comment]
That’s in fact something that I did on purpose, because simple field blocks are always mandatory.
The asterisks are only shown on struct blocks.
