### ISSUE TITLE
Page Chooser bug while editing page

### ISSUE THREAD

**Issue by dniegel** [noripyt/wagtail-react-streamfield#21]
While editing an existing page with an already saved PageChooserBlock, a click on 'Choose another page' does not open the page chooser modal. The parent page id in the GET request is not a number:

![page chooser page id bug](https://user-images.githubusercontent.com/45167324/48706651-2e400180-ebfd-11e8-9bca-c39e34006b01.png)

Possible reason in page-chooser.js, line 53

`parentId: data.meta.parent`

(parent is an object)

**Comment by BertrandBordage** [comment]
Fixed by #23.
