### ISSUE TITLE
Validation error messages for stream fields not shown

### ISSUE THREAD

**Issue by dniegel** [noripyt/wagtail-react-streamfield#22]
When trying to save a page with an invalid stream field (e.g. required blocks missing or less / more blocks than allowed inside the stream field), the error message/s is/are not shown

![validation error message for stream field missing](https://user-images.githubusercontent.com/45167324/49094919-a646a100-f267-11e8-8a07-6e2fc29e2dca.png)

This might arise from this: in 'classic' wagtail, the error messages (block_errors) are contained in the 'sequence-container' (admin\templates\wagtailadmin\block_forms\sequence.html) which does not appear with wagtail-react-streamfield installed.

**Comment by BertrandBordage** [comment]
Fixed by bf57687e1bd9e10bb788a6ab7c2c9be1cc4c472e.
