### ISSUE TITLE
DateTime format for DateTimeBlock is not loaded correctly

### ISSUE THREAD

**Issue by dniegel** [noripyt/wagtail-react-streamfield#25]
Hi,

it seems there is a bug for DateTimeBlock (from wagtail.core.blocks), when a page containing it is edited or after the first save, saving again is resulting in a validation error:

![datetime_format_bug](https://user-images.githubusercontent.com/45167324/49808705-7d410880-fd5d-11e8-805e-d5688eee6b9b.png)

Version: 1.0.5

Steps to reproduce:

1) Create a page with a stream field with a DateTimeBlock option

2) Choose any valid DateTime and save

3) The DateTime format should be incorrect now / trying to save again should produce a 	validation error.

The reason for this behaviour might be the usage of the InputJSONEncoder / DjangoJSONEncoder (in function render_with_errors) which uses isoformat().

**Comment by ChristophTr** [comment]
Same here.

**Comment by BertrandBordage** [comment]
Fixed by b552ee9d0a966f9a81bb0fdbaeec8a830996c766 and released in 1.0.6 :)
