### ISSUE TITLE
Doesn't start collapsed anymore

### ISSUE THREAD

**Issue by Adrian-Turjak** [noripyt/wagtail-react-streamfield#28]
One of the older versions started collapsed (only one line for each mainblock) and only would open it up when you click on it.

I jumped to version 1.1.0 and it seems to started opened, which for pages with A LOT of blocks is worse.

Is this a bug, or something I can control?

**Comment by BertrandBordage** [comment]
There is a way @Adrian-Turjak, just not documented yet ;)
See https://github.com/noripyt/wagtail-react-streamfield/issues/13#issuecomment-443483114
