### ISSUE TITLE
customise the structblock form

### ISSUE THREAD

**Issue by Designer023** [noripyt/wagtail-react-streamfield#33]
Really loving the new UI for the streamfields. Fantactic work. It makes editing so much better, however the customisations I had made for a StructBlock are no longer working as they were before the plugin was installed. Not sure if this is an error or not, or perhaps not part of the upgrades to the streamfield. Will this still be possible to do, and if so how?

I was using:
```
class Meta:
        form_template = 'global_utils/forms/column_form.html'
```

Just wanted to flag it and ask the question just in case?

**Comment by BertrandBordage** [comment]
This was possible in earlier versions of this whole project, but I had to take the decision of temporarily disabling that because of other compatibility issues (with inline JS in such forms). I will see if I can restore this possibility in the upcoming days.

**Comment by Designer023** [comment]
Hi @BertrandBordage thank you for getting back me about the changes. If there's compatibility issues then don't worry about it. It's only a minor layout nicety in the admin so it's by no means a deal breaker.

**Comment by BertrandBordage** [comment]
Marking it as won’t fix for now. Support may be introduced again, but I doubt it, it goes a little against the direction we are taking with Wagtail.
